project_id = "qgtaqimxuqogkrkkredn"

[functions.google-oauth]
verify_jwt = true

[functions.sync-calendar]
verify_jwt = true

[functions.create-meet-link]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.process-scheduled-emails]
verify_jwt = false

[functions.create-email-schedule]
verify_jwt = true

[functions.suggest-ecas]
verify_jwt = true